### ISSUE TITLE
Research for Cucumber Tests 

### ISSUE THREAD

**Issue by MuneebNasir** [MuneebNasir/Amazin-online-bookstore-OA#71]
**Is your feature request related to a problem? Please describe.**
Research into Cucumber test cases for the developed code 

**Describe the solution you'd like**
Research & understand the testing technique and create test case with Cucumber

**Describe alternatives you've considered**
N/A

**Additional context**
Cucumber Testing relates to final oral presentation for the group

**Comment by MuneebNasir** [comment]
Currently doing research on this for the integration into the main application for the final product. This might be helpful https://github.com/pzavolinsky/react-cucumber

**Comment by MuneebNasir** [comment]
Research done, will now move on to integrating tests in the M3

**Comment by decarbonite** [comment]
There are two way to approach this. Using Cucumber JVM for Java where we will create java test classes and use a framework to interact with the browser like Selenium. Or using the Nodejs version of Cucumber which you pointed out where we will write the tests in JavaScript. I think the prof might want us to do the Java approach since he mentioned JS is not the main part of this course, or maybe it is up to us. It would be best to ask the TA/Prof before we start this.

**Comment by MuneebNasir** [comment]
> There are two way to approach this. Using Cucumber JVM for Java where we will create java test classes and use a framework to interact with the browser like Selenium. Or using the Nodejs version of Cucumber which you pointed out where we will write the tests in JavaScript. I think the prof might want us to do the Java approach since he mentioned JS is not the main part of this course, or maybe it is up to us. It would be best to ask the TA/Prof before we start this.

Absolutely agree with you. Personally i think approaching this with Java and Selenium would be a better approach in terms of course work. Lets bring this up in tomorrow's meeting.
